image: python:3.11-slim

stages:
  - test

validate:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -e ".[dev]"
    - python -m pytest -q
    - python -m ruff check .
    #    - python -m ruff format --check .
    - python -m build
