def write_valid_config(env_file):
    env_file.write_text(
        "\n".join(
            [
                "CONNECTOR_DOMAIN=connector.test.local",
                "PARTICIPANT_DID=did:web:connector.test.local:participant",
                "PARTICIPANT_CONTEXT_ID=participant",
                "TRUSTED_ISSUER_DID=did:web:issuer.test.local:issuer",
                "WALLET_IDENTITY_API=http://127.0.0.1:20100/api/identity",
                "WALLET_SUPERUSER_KEY=YWRtaW4.test-token",
                "VAULT_TOKEN=test-vault-token",
                "CONNECTOR_MANAGEMENT_API_KEY=test-management-api-key",
                "PARTICIPANT_DSP_CALLBACK_ADDRESS=https://connector.test.local/dsp",
                "PARTICIPANT_DATAPLANE_PUBLIC_URL=https://connector.test.local/public",
                "CONNECTOR_ONBOARDING_STATE=.state/participant.json",
            ]
        ),
        encoding="utf-8",
    )
    pass
