shared:
    connectorId: &connectorId did:web:provider-wallet.staging.construct-x.net:provider
    secretAlias: &secretAlias providersecret
    trustedIssuerId: &trustedIssuerId did:web:issuer.staging.construct-x.net:issuer
    clusterIssuer: &clusterIssuer letsencrypt-staging
    ingressClass: &ingressClass nginx
    imagePullSecret: &imagePullSecret registry-creds
    controlplaneFqdn: &controlplaneFqdn provider-edc-controlplane.staging.construct-x.net
    dataplaneFqdn: &dataplaneFqdn provider-edc-dataplane.staging.construct-x.net

nameOverride: provider-edc
fullnameOverride: provider-edc

participant:
    id: *connectorId

iatp:
    id: *connectorId
    trustedIssuerId: *trustedIssuerId
    trustedIssuers:
        - id: *trustedIssuerId
    sts:
        oauth:
            token_url: https://provider-wallet.staging.construct-x.net/api/sts/token
            client:
                id: *connectorId
                secret_alias: *secretAlias
    didService:
        selfRegistration:
            id: *connectorId

controlplane:
    hostname: provider-edc-controlplane
    imagePullSecrets:
        - name: *imagePullSecret
    ingresses:
        ## Public / Internet facing Ingress
        - enabled: true
          hostname: *controlplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *controlplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - protocol
          className: *ingressClass
          tls:
              enabled: true
              secretName: provider-edc-cp-tls
          certManager:
              clusterIssuer: *clusterIssuer
        ## Private / Intranet facing Ingress
        - enabled: false
          hostname: *controlplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *controlplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - management
              - control
              - validation
              - metrics
          className: *ingressClass
          tls:
              enabled: true
              secretName: provider-edc-cp-int-tls
          certManager:
              clusterIssuer: *clusterIssuer

dataplane:
    hostname: provider-edc-dataplane
    imagePullSecrets:
        - name: *imagePullSecret
    token:
        signer:
            privatekey_alias: prov_priv
        verifier:
            publickey_alias: prov_pub
    ingresses:
        ## Public / Internet facing Ingress
        - enabled: true
          hostname: *dataplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *dataplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - public
              - proxy
          className: *ingressClass
          tls:
              enabled: true
              secretName: provider-edc-dp-tls
          certManager:
              clusterIssuer: *clusterIssuer
        ## Private / Intranet facing Ingress
        - enabled: false
          hostname: *dataplaneFqdn
          annotations:
              cert-manager.io/cluster-issuer: *clusterIssuer
              external-dns.alpha.kubernetes.io/hostname: *dataplaneFqdn
              external-dns.alpha.kubernetes.io/ttl: "300"
          endpoints:
              - management
              - control
              - metrics
          className: *ingressClass
          tls:
              enabled: true
              secretName: provider-edc-dp-int-tls
          certManager:
              clusterIssuer: *clusterIssuer

postgresql:
    persistence:
        enabled: true
        size: 10Gi
        storageClass: ""

vault:
    hashicorp:
        init:
            enabled: true