# Copyright (c) 2026 Bergische Universität Wuppertal
# SPDX-License-Identifier: Apache-2.0

services:
  traefik:
    command:
      - --api.dashboard=false
      - --ping=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=${STACK_NAME}-network
      - --entrypoints.websecure.address=:443
      - --accesslog=true
    ports: !override []
    networks:
      edc-network:
      edge-ingress:
        aliases:
          - constructx-edc

networks:
  edge-ingress:
    name: tmdt-edge-ingress
    external: true
